tap 'homebrew/core'
tap 'homebrew/services'
tap 'caskroom/cask'
tap 'caskroom/fonts'

brew 'direnv'
brew 'gpg'
brew 'nmap'
brew 'ag'
brew 'jq'
brew 'golang'
brew 'p7zip'
brew 'pinentry-mac'
brew 'mas'
brew 'zsh'
brew 'neovim'
cask 'tunnelblick'
cask 'macdown'
cask 'transmission'
cask 'font-inconsolata-nerd-font'
cask 'wireshark'
cask 'steam'
cask 'skype'
cask 'docker'
cask 'flux'
cask 'vlc'
cask 'slack'
cask 'softu2f'
cask 'google-chrome'
cask 'telegram'
cask 'spotify'
mas 'slack', id: 803453959
mas 'telegram', id: 946399090
